# This file was generated by GoReleaser. DO NOT EDIT.
cask "nnn" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "beaa143bb26c113fe9bb533b9f53aed32f18696fcdec1d88d78fdd2a9e5462d4"
      url "https://github.com/antoniocali/nnn/releases/download/v#{version}/nnn_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "40a38df7bbe3ab3f2fa5c9556df810959a5e7412d8fb3d011f6f7fd81ac04c14"
      url "https://github.com/antoniocali/nnn/releases/download/v#{version}/nnn_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "af7f8dfca042ba205f6faed781926fc6181e0737a75201a81933722092ecf055"
      url "https://github.com/antoniocali/nnn/releases/download/v#{version}/nnn_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "675507ef85a980387a884e92a40962c95824e96a3e8670a71a3b2edbf328942a"
      url "https://github.com/antoniocali/nnn/releases/download/v#{version}/nnn_linux_arm64.tar.gz"
    end
  end

  name "nnn"
  desc "A beautiful terminal note manager"
  homepage "https://github.com/antoniocali/nnn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nnn"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nnn"]
    end
  end

  # No zap stanza required

end
