# This file was generated by GoReleaser. DO NOT EDIT.
cask "nnn" do
  name "nnn"
  desc "A beautiful terminal note manager"
  homepage "https://github.com/antoniocali/nnn"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nnn"

  on_macos do
    on_intel do
      url "https://github.com/antoniocali/nnn/releases/download/v#{version}/nnn_darwin_x86_64.tar.gz"
      sha256 "004cd4fa6e2044972bb1bca6e7eb0503f4039eb404559b1a3851a2afd07bae19"
    end
    on_arm do
      url "https://github.com/antoniocali/nnn/releases/download/v#{version}/nnn_darwin_arm64.tar.gz"
      sha256 "6f92f7db080a860171ae0a7ecb502497e69c6f084ba05f5fc5b26375e659a5e1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antoniocali/nnn/releases/download/v#{version}/nnn_linux_x86_64.tar.gz"
      sha256 "e9ecde58a3747e1df5fb4c9458aeb748c737cffc0b11ed11b2b41e31bde9405d"
    end
    on_arm do
      url "https://github.com/antoniocali/nnn/releases/download/v#{version}/nnn_linux_arm64.tar.gz"
      sha256 "b2ffa20435168d2a5f8402098e60705931f73e83799bba47f1e4f56cf99679ad"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nnn"]
    end
  end

  # No zap stanza required
end
