# This file was generated by GoReleaser. DO NOT EDIT.
cask "nnn" do
  name "nnn"
  desc "A beautiful terminal note manager"
  homepage "https://github.com/antoniocali/nnn"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nnn"

  on_macos do
    on_intel do
      url "https://github.com/antoniocali/nnn/releases/download/v#{version}/nnn_darwin_x86_64.tar.gz"
      sha256 "7d30cd6c559a0957e9691d2fab240e8cfd256eb621d277cd6a70b17c1fbf2212"
    end
    on_arm do
      url "https://github.com/antoniocali/nnn/releases/download/v#{version}/nnn_darwin_arm64.tar.gz"
      sha256 "03bdee31c4554917c0db6b11e44a6723fb187eada7163195cb8b4798e9cd3567"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antoniocali/nnn/releases/download/v#{version}/nnn_linux_x86_64.tar.gz"
      sha256 "5bcfb8bc47ec60dca7b2cd2e98edbfd537469e2a5bd29681ad6244e62b24a131"
    end
    on_arm do
      url "https://github.com/antoniocali/nnn/releases/download/v#{version}/nnn_linux_arm64.tar.gz"
      sha256 "21c0e761dd23f7f6ba89017a009d266283ef8db88f9af241ccce8d20fe1a528f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nnn"]
    end
  end

  # No zap stanza required
end
