# This file was generated by GoReleaser. DO NOT EDIT.
cask "terafrom" do
  name "terafrom"
  desc "A drop-in replacement for terraform plan/apply with clean, readable diff output"
  homepage "https://github.com/antoniocali/terafrom"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terafrom"

  on_macos do
    on_intel do
      url "https://github.com/antoniocali/terafrom/releases/download/v#{version}/terafrom_darwin_x86_64.tar.gz"
      sha256 "bb8546c4cafccb4580308f98cf17124f6c1b3947497891bd9cc0dc6e2ddf8484"
    end
    on_arm do
      url "https://github.com/antoniocali/terafrom/releases/download/v#{version}/terafrom_darwin_arm64.tar.gz"
      sha256 "ddd05c863d9e1286528a86d21b6bb535514acf666ee4762409a73bb8993dc18e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antoniocali/terafrom/releases/download/v#{version}/terafrom_linux_x86_64.tar.gz"
      sha256 "bc591f920512cf2ab98a0261805f887d29973ca5c2dcee7224ce4adc6161f63f"
    end
    on_arm do
      url "https://github.com/antoniocali/terafrom/releases/download/v#{version}/terafrom_linux_arm64.tar.gz"
      sha256 "1a78badae6f0de90c20105659cd4edb9c0c2418ed16660e49edefa56d7283bde"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terafrom"]
    end
  end

  # No zap stanza required
end
