# This file was generated by GoReleaser. DO NOT EDIT.
cask "terafrom" do
  name "terafrom"
  desc "A drop-in replacement for terraform plan/apply with clean, readable diff output"
  homepage "https://github.com/antoniocali/terafrom"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terafrom"

  on_macos do
    on_intel do
      url "https://github.com/antoniocali/terafrom/releases/download/v#{version}/terafrom_darwin_x86_64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_arm do
      url "https://github.com/antoniocali/terafrom/releases/download/v#{version}/terafrom_darwin_arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antoniocali/terafrom/releases/download/v#{version}/terafrom_linux_x86_64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_arm do
      url "https://github.com/antoniocali/terafrom/releases/download/v#{version}/terafrom_linux_arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terafrom"]
    end
  end

  # No zap stanza required
end
