# This file was generated by GoReleaser. DO NOT EDIT.
cask "terafrom" do
  name "terafrom"
  desc "A drop-in replacement for terraform plan/apply with clean, readable diff output"
  homepage "https://github.com/antoniocali/terafrom"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terafrom"

  on_macos do
    on_intel do
      url "https://github.com/antoniocali/terafrom/releases/download/v#{version}/terafrom_darwin_x86_64.tar.gz"
      sha256 "30a6905ae03c760fa96183804ad62b869bd1bec3c5a6a75e65f51da10b01ae3b"
    end
    on_arm do
      url "https://github.com/antoniocali/terafrom/releases/download/v#{version}/terafrom_darwin_arm64.tar.gz"
      sha256 "c2d02072246706feed47f2f0b1dbdcc2d48c9c945b35eef4571049878a25bc33"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/antoniocali/terafrom/releases/download/v#{version}/terafrom_linux_x86_64.tar.gz"
      sha256 "04cd287047b0e50605c983c1f648161be17bd6a700c8ffffa462776c36986bc2"
    end
    on_arm do
      url "https://github.com/antoniocali/terafrom/releases/download/v#{version}/terafrom_linux_arm64.tar.gz"
      sha256 "6b806c5e33b533af66dc8cad350ebd3cccf6071135b35cdb97e85476ce3bc87b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terafrom"]
    end
  end

  # No zap stanza required
end
